#!/usr/bin/env bash
set -e

filename="/home/$(whoami)/.gh-packer"

help() {
  cat <<EOF
  Install and remove extensions from ~/.gh-packer file  
  Example: `gh packer -i` Install missed extensions    
  Example: `gh packer -r` Remove all extensions  
EOF
}


install_extension() {
  echo Install...
  while read p; do
    (gh extension list | grep "$p") &>/dev/null || gh extension install "$p"
  done < "$filename"
  printf "\033[0;32m✓\033[0m Done\n"
}

full_remove() {
  echo Remove...
  while read p; do
    gh extension remove "$p"
  done < "$filename"
  printf "\033[0;32m✓\033[0m Done\n"
}

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      help
      exit 0
      ;;
    -i)
      install_extension
      exit 0
      ;;
    -r)
      full_remove
      exit 0
      ;;
    *)
  esac
  shift
done

help
exit 0
